prestashop:
  build: .
  container_name: {CONTAINER_NAME_WEB}
  ports:
    - "{PORT_WEB}:80"
  links:
    - smtp
    - mysql
  env_file:
    - ./conf/env_file/production/env
  labels:
    - "com.hipay.github={label}"
    - "com.hipay.circleci={circleci}"
mysql:
  container_name: {CONTAINER_NAME_MYSQL}
  image: mysql:5.6.23
  env_file:
    - ./conf/env_file/production/env
  ports:
    - "{PORT_MYSQL}:3306"
smtp:
  container_name: {CONTAINER_NAME_SMTP}
  ports:
    - "{PORT_SMTP}:1080"