prestashop:
  container_name: jira-tpp-1619.hipay-pos-platform.com
  build: .
  ports:
    - "8202:80"
  links:
    - smtp
  environment:
    PS_DOMAIN: jira-tpp-1619.hipay-pos-platform.com
    ADMIN_MAIL: demo@hipay.com
    ADMIN_PASSWD: hipay123
    PS_LANGUAGE: en
    PS_COUNTRY: gb
    PS_INSTALL_AUTO: 1
    PS_DEV_MODE: 1
    PS_FOLDER_ADMIN: admin-hipay
    PS_FOLDER_INSTALL: installOLD
smtp:
  image: schickling/mailcatcher
  container_name: smtp-hipay-enterprise-ps1619
  ports:
    - "1102:1080"